// SPDX-License-Identifier: MIT
import { z } from "zod";

const cslJsonNameSchema = z.object({
  family: z.string().optional(),
  given: z.string().optional(),
  "dropping-particle": z.string().optional(),
  "non-dropping-particle": z.string().optional(),
  suffix: z.string().optional(),
  "comma-suffix": z.string().or(z.number()).or(z.boolean()).optional(),
  "static-ordering": z.string().or(z.number()).or(z.boolean()).optional(),
  literal: z.string().optional(),
  "parse-names": z.string().or(z.number()).or(z.boolean()).optional(),
});

const cslJsonDateSchema = z.object({
  "date-parts": z
    .array(z.array(z.string().or(z.number())).min(1).max(3))
    .min(1)
    .max(2)
    .optional(),
  season: z.string().or(z.number()).optional(),
  circa: z.string().or(z.number()).or(z.boolean()).optional(),
  literal: z.string().optional(),
  raw: z.string().optional(),
});

const cslJsonItemSchema = z.object({
  type: z.literal([
    "article",
    "article-journal",
    "article-magazine",
    "article-newspaper",
    "bill",
    "book",
    "broadcast",
    "chapter",
    "classic",
    "collection",
    "dataset",
    "document",
    "entry",
    "entry-dictionary",
    "entry-encyclopedia",
    "event",
    "figure",
    "graphic",
    "hearing",
    "interview",
    "legal_case",
    "legislation",
    "manuscript",
    "map",
    "motion_picture",
    "musical_score",
    "pamphlet",
    "paper-conference",
    "patent",
    "performance",
    "periodical",
    "personal_communication",
    "post",
    "post-weblog",
    "regulation",
    "report",
    "review",
    "review-book",
    "software",
    "song",
    "speech",
    "standard",
    "thesis",
    "treaty",
    "webpage",
  ]),
  id: z.string().or(z.number()),
  "citation-key": z.string().optional(),
  categories: z.array(z.string()).optional(),
  language: z.string().optional(),
  journalAbbreviation: z.string().optional(),
  shortTitle: z.string().optional(),
  author: z.array(cslJsonNameSchema).optional(),
  chair: z.array(cslJsonNameSchema).optional(),
  "collection-editor": z.array(cslJsonNameSchema).optional(),
  compiler: z.array(cslJsonNameSchema).optional(),
  composer: z.array(cslJsonNameSchema).optional(),
  "container-author": z.array(cslJsonNameSchema).optional(),
  contributor: z.array(cslJsonNameSchema).optional(),
  curator: z.array(cslJsonNameSchema).optional(),
  director: z.array(cslJsonNameSchema).optional(),
  editor: z.array(cslJsonNameSchema).optional(),
  "editorial-director": z.array(cslJsonNameSchema).optional(),
  "executive-producer": z.array(cslJsonNameSchema).optional(),
  guest: z.array(cslJsonNameSchema).optional(),
  host: z.array(cslJsonNameSchema).optional(),
  interviewer: z.array(cslJsonNameSchema).optional(),
  illustrator: z.array(cslJsonNameSchema).optional(),
  narrator: z.array(cslJsonNameSchema).optional(),
  organizer: z.array(cslJsonNameSchema).optional(),
  "original-author": z.array(cslJsonNameSchema).optional(),
  performer: z.array(cslJsonNameSchema).optional(),
  producer: z.array(cslJsonNameSchema).optional(),
  recipient: z.array(cslJsonNameSchema).optional(),
  "reviewed-author": z.array(cslJsonNameSchema).optional(),
  "script-writer": z.array(cslJsonNameSchema).optional(),
  "series-creator": z.array(cslJsonNameSchema).optional(),
  translator: z.array(cslJsonNameSchema).optional(),
  accessed: cslJsonDateSchema.optional(),
  "available-date": cslJsonDateSchema.optional(),
  "event-date": cslJsonDateSchema.optional(),
  issued: cslJsonDateSchema.optional(),
  "original-date": cslJsonDateSchema.optional(),
  submitted: cslJsonDateSchema.optional(),
  abstract: z.string().optional(),
  annote: z.string().optional(),
  archive: z.string().optional(),
  archive_collection: z.string().optional(),
  archive_location: z.string().optional(),
  "archive-place": z.string().optional(),
  authority: z.string().optional(),
  "call-number": z.string().optional(),
  "chapter-number": z.string().or(z.number()).optional(),
  "citation-number": z.string().or(z.number()).optional(),
  "citation-label": z.string().optional(),
  "collection-number": z.string().or(z.number()).optional(),
  "collection-title": z.string().optional(),
  "container-title": z.string().optional(),
  "container-title-short": z.string().optional(),
  dimensions: z.string().optional(),
  division: z.string().optional(),
  DOI: z.string().optional(),
  edition: z.string().or(z.number()).optional(),
  event: z.string().optional(),
  "event-title": z.string().optional(),
  "event-place": z.string().optional(),
  "first-reference-note-number": z.string().or(z.number()).optional(),
  genre: z.string().optional(),
  ISBN: z.string().optional(),
  ISSN: z.string().optional(),
  issue: z.string().or(z.number()).optional(),
  jurisdiction: z.string().optional(),
  keyword: z.string().optional(),
  locator: z.string().or(z.number()).optional(),
  medium: z.string().optional(),
  note: z.string().optional(),
  number: z.string().or(z.number()).optional(),
  "number-of-pages": z.string().or(z.number()).optional(),
  "number-of-volumes": z.string().or(z.number()).optional(),
  "original-publisher": z.string().optional(),
  "original-publisher-place": z.string().optional(),
  "original-title": z.string().optional(),
  page: z.string().or(z.number()).optional(),
  "page-first": z.string().or(z.number()).optional(),
  part: z.string().or(z.number()).optional(),
  "part-title": z.string().optional(),
  PMCID: z.string().optional(),
  PMID: z.string().optional(),
  printing: z.string().or(z.number()).optional(),
  publisher: z.string().optional(),
  "publisher-place": z.string().optional(),
  references: z.string().optional(),
  "reviewed-genre": z.string().optional(),
  "reviewed-title": z.string().optional(),
  scale: z.string().optional(),
  section: z.string().optional(),
  source: z.string().optional(),
  status: z.string().optional(),
  supplement: z.string().or(z.number()).optional(),
  title: z.string().optional(),
  "title-short": z.string().optional(),
  URL: z.string().optional(),
  version: z.string().optional(),
  volume: z.string().or(z.number()).optional(),
  "volume-title": z.string().optional(),
  "volume-title-short": z.string().optional(),
  "year-suffix": z.string().optional(),
  custom: z.json().optional(),
});

export const cslJsonSchema = z.array(cslJsonItemSchema);

export type CslJsonName = z.infer<typeof cslJsonNameSchema>;
export type CslJsonDate = z.infer<typeof cslJsonDateSchema>;
export type CslJsonItem = z.infer<typeof cslJsonItemSchema>;
export type CslJson = z.infer<typeof cslJsonSchema>;

export function validateCslJson(input: unknown): CslJson {
  return cslJsonSchema.parse(input);
}

export function parseCslJson(input: string): CslJson {
  return validateCslJson(JSON.parse(input));
}
